sudo: false
language: java
jdk: oraclejdk7

env:
  global:
  - HUB=2.2.0

install:
- curl -LO "https://github.com/github/hub/releases/download/v$HUB/hub-linux-amd64-$HUB.tar.gz"
- tar -C "$HOME" -zxf "hub-linux-amd64-$HUB.tar.gz"
- export PATH="$PATH:$HOME/hub-linux-amd64-$HUB"

- mkdir -p "$HOME/.config"
- echo "https://${GH_TOKEN}:@github.com" > "$HOME/.config/git-credential"
- echo "github.com:" > "$HOME/.config/hub"
- echo "-" "oauth_token:" "$GH_TOKEN" >> "$HOME/.config/hub"

- hub config --global user.name  "${GH_USER}"
- hub config --global user.email "${GH_USER}@users.noreply.github.com"
- hub config --global hub.protocol "https"
- hub config --global hub.user "$GH_USER"
- hub config --global credential.helper "store --file=$HOME/.config/git-credential"
- hub config --global core.autocrlf "input"
- hub config --global push.default "current"

- unset GH_USER
- unset GH_USER_EMAIL
- unset GH_USER_NAME
- unset GH_TOKEN

script:        ./gradlew check asciidoctor
after_success: ./core/src/docs/shell/release.sh
before_deploy: ./gradlew shadowJar bintrayUpload

deploy:
  provider: releases
  api_key:
    secure: jlJklyZsCT+A+qZCSb89/qQ+CeeS0V9x1Gq27dvsXYBu8805st+JbSqUFZddiWe9xR7sz5mZhrNT5v4LengSbrwHz43JuSNEKzdu7F2yfGCGbWL7aKEk46deqOCzw4l9djT9ZWO/e8tw5YYzLNc1OhGtdkZq2o+HqhwL0yyoYHs=
  skip_cleanup: true
  file_glob: true
  file: cli/build/libs/gssh.jar
  on:
    tags: true
    all_branches: true
