sudo: false
language: java
jdk: oraclejdk7

env:
  global:
  - HUB=2.2.0

install:
- curl -LO "https://github.com/github/hub/releases/download/v$HUB/hub-linux-amd64-$HUB.tar.gz"
- tar -C "$HOME" -zxf "hub-linux-amd64-$HUB.tar.gz"
- export PATH="$PATH:$HOME/hub-linux-amd64-$HUB"

- mkdir -p "$HOME/.config"
- echo "https://${GH_TOKEN}:@github.com" > "$HOME/.config/git-credential"
- echo "github.com:" > "$HOME/.config/hub"
- echo "-" "oauth_token:" "$GH_TOKEN" >> "$HOME/.config/hub"

- hub config --global user.name  "${GH_USER}"
- hub config --global user.email "${GH_USER}@users.noreply.github.com"
- hub config --global hub.protocol "https"
- hub config --global hub.user "$GH_USER"
- hub config --global credential.helper "store --file=$HOME/.config/git-credential"
- hub config --global core.autocrlf "input"
- hub config --global push.default "current"

- unset GH_USER
- unset GH_USER_EMAIL
- unset GH_USER_NAME
- unset GH_TOKEN

- mkdir -m 700 -p -v $HOME/.ssh
- echo '-----BEGIN RSA PRIVATE KEY-----'        >> $HOME/.ssh/id_rsa
- echo "$INTEGRATION_TEST_SSH_KEY" | fold -w 76 >> $HOME/.ssh/id_rsa
- echo '-----END RSA PRIVATE KEY-----'          >> $HOME/.ssh/id_rsa
- chmod -v 600 $HOME/.ssh/id_rsa
- cp -av $HOME/.ssh/id_rsa{,_passphrase}
- if [ "$INTEGRATION_TEST_SSH_HOST" ]; then ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=ssh-rsa -o UserKnownHostsFile=$HOME/.ssh/known_hosts -i $HOME/.ssh/id_rsa "${INTEGRATION_TEST_SSH_USER}@${INTEGRATION_TEST_SSH_HOST}" id; fi
- if [ "$INTEGRATION_TEST_SSH_HOST" ]; then ssh-keygen -H -F "${INTEGRATION_TEST_SSH_HOST}"; fi
- if [ "$INTEGRATION_TEST_SSH_HOST" ]; then ssh-keygen -p -N pass1234 -f "$HOME/.ssh/id_rsa_passphrase"; fi

- unset INTEGRATION_TEST_SSH_KEY


script:
- ./gradlew check asciidoctor
- eval $(ssh-agent)
- if [ "$INTEGRATION_TEST_SSH_HOST" ]; then ssh-add $HOME/.ssh/id_rsa; fi
- if [ "$INTEGRATION_TEST_SSH_HOST" ]; then ./gradlew :os-integration-test-with-agent:check; fi
- ssh-agent -k

after_success: ./gradle/release-docs.sh
after_script:  ./gradle/release-reports.sh
before_deploy: ./gradlew shadowJar bintrayUpload

deploy:
  provider: releases
  api_key:
    secure: jlJklyZsCT+A+qZCSb89/qQ+CeeS0V9x1Gq27dvsXYBu8805st+JbSqUFZddiWe9xR7sz5mZhrNT5v4LengSbrwHz43JuSNEKzdu7F2yfGCGbWL7aKEk46deqOCzw4l9djT9ZWO/e8tw5YYzLNc1OhGtdkZq2o+HqhwL0yyoYHs=
  skip_cleanup: true
  file_glob: true
  file: cli/build/libs/gssh.jar
  on:
    tags: true
    all_branches: true
