sudo: false
language: java
jdk: oraclejdk7

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2

env:
- JAVA_OPTS="-Xmx1024m -Xms1024m"

install:
- mkdir -p "$HOME/.config"
- echo "https://${GH_TOKEN}:@github.com" > "$HOME/.config/git-credential"

- git config --global user.name  "${GH_USER}"
- git config --global user.email "${GH_USER}@users.noreply.github.com"
- git config --global credential.helper "store --file=$HOME/.config/git-credential"
- git config --global core.autocrlf "input"
- git config --global push.default "current"

- unset GH_USER
- unset GH_USER_EMAIL
- unset GH_USER_NAME
- unset GH_TOKEN

- mkdir -m 700 -p -v $HOME/.ssh
- echo '-----BEGIN RSA PRIVATE KEY-----'        >> "$HOME/.ssh/id_ext"
- echo "$EXT_SSH_KEY" | fold -w 76              >> "$HOME/.ssh/id_ext"
- echo '-----END RSA PRIVATE KEY-----'          >> "$HOME/.ssh/id_ext"
- chmod -v 600 "$HOME/.ssh/id_ext"
- unset EXT_SSH_KEY

- ./os-integration-test/setup-external-ssh.sh


script:
- ./gradlew check asciidoctor publishToMavenLocal

- git clone --depth 1 https://github.com/int128/gradle-ssh-plugin
  && pushd gradle-ssh-plugin
  && sed -i -e "s,groovy-ssh:[0-9.]*,groovy-ssh:${TRAVIS_TAG:-SNAPSHOT},g" build.gradle
  && git diff
  && ./gradlew -Ptarget.gradle.versions=1.12 check
- popd


after_success:
- test "$TRAVIS_BRANCH" = "master"
  && pushd docs/build/asciidoc/html5
  && git init
  && git add .
  && git commit -m "Release from $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH"
  && git remote add origin https://github.com/gradle-ssh-plugin/docs
  && git branch -m gh-pages
  && git push -f origin gh-pages
- popd


after_script:
- mkdir -vp build/reports
  && for d in */build/reports/tests; do cp -av "$d" "build/reports/${d%%/*}"; done
  && pushd build/reports
  && git init
  && git add .
  && git commit -m "Release from $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH"
  && git remote add origin https://github.com/groovy-ssh/reports
  && git branch -m gh-pages
  && git push -f origin gh-pages
- popd


before_deploy:
- ./gradlew bintrayUpload

- pushd gradle-ssh-plugin
  && git checkout -b "groovy-ssh-$TRAVIS_TAG"
  && sed -i -e "s,groovy-ssh:[0-9.]*,groovy-ssh:$TRAVIS_TAG,g" build.gradle
  && git add .
  && git commit -m "Groovy SSH $TRAVIS_TAG"
  && git push origin "groovy-ssh-$TRAVIS_TAG"
- popd


deploy:
  provider: releases
  api_key:
    secure: jlJklyZsCT+A+qZCSb89/qQ+CeeS0V9x1Gq27dvsXYBu8805st+JbSqUFZddiWe9xR7sz5mZhrNT5v4LengSbrwHz43JuSNEKzdu7F2yfGCGbWL7aKEk46deqOCzw4l9djT9ZWO/e8tw5YYzLNc1OhGtdkZq2o+HqhwL0yyoYHs=
  skip_cleanup: true
  file_glob: true
  file: cli/build/libs/gssh.jar
  on:
    tags: true
    all_branches: true
