sudo: false
language: java
jdk: oraclejdk7

install:
- mkdir -p "$HOME/.config"
- echo "https://${GH_TOKEN}:@github.com" > "$HOME/.config/git-credential"

- git config --global user.name  "${GH_USER}"
- git config --global user.email "${GH_USER}@users.noreply.github.com"
- git config --global credential.helper "store --file=$HOME/.config/git-credential"
- git config --global core.autocrlf "input"
- git config --global push.default "current"

- unset GH_USER
- unset GH_USER_EMAIL
- unset GH_USER_NAME
- unset GH_TOKEN

- mkdir -m 700 -p -v $HOME/.ssh
- echo '-----BEGIN RSA PRIVATE KEY-----'        >> $HOME/.ssh/id_rsa
- echo "$INTEGRATION_TEST_SSH_KEY" | fold -w 76 >> $HOME/.ssh/id_rsa
- echo '-----END RSA PRIVATE KEY-----'          >> $HOME/.ssh/id_rsa
- chmod -v 600 $HOME/.ssh/id_rsa
- cp -av $HOME/.ssh/id_rsa{,_passphrase}
- test "$INTEGRATION_TEST_SSH_HOST" && ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=ssh-rsa -o UserKnownHostsFile=$HOME/.ssh/known_hosts -i $HOME/.ssh/id_rsa "${INTEGRATION_TEST_SSH_USER}@${INTEGRATION_TEST_SSH_HOST}" id
- test "$INTEGRATION_TEST_SSH_HOST" && ssh-keygen -H -F "${INTEGRATION_TEST_SSH_HOST}"
- test "$INTEGRATION_TEST_SSH_HOST" && ssh-keygen -p -N pass1234 -f "$HOME/.ssh/id_rsa_passphrase"

- unset INTEGRATION_TEST_SSH_KEY


script:
- ./gradlew check asciidoctor publishMavenPublicationToMavenLocal shadowJar
- java -jar cli/build/libs/gssh.jar gradle-plugin-integration-test.groovy


after_success:
- test "$TRAVIS_BRANCH" = "master"
  && cd docs/build/asciidoc/html5
  && git init
  && git add .
  && git commit -m "Release from $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH"
  && git remote add origin https://github.com/gradle-ssh-plugin/docs
  && git branch -m gh-pages
  && git push -f origin gh-pages
  && cd ..


after_script:  ./gradle/release-reports.sh
before_deploy: ./gradlew bintrayUpload

deploy:
  provider: releases
  api_key:
    secure: jlJklyZsCT+A+qZCSb89/qQ+CeeS0V9x1Gq27dvsXYBu8805st+JbSqUFZddiWe9xR7sz5mZhrNT5v4LengSbrwHz43JuSNEKzdu7F2yfGCGbWL7aKEk46deqOCzw4l9djT9ZWO/e8tw5YYzLNc1OhGtdkZq2o+HqhwL0yyoYHs=
  skip_cleanup: true
  file_glob: true
  file: cli/build/libs/gssh.jar
  on:
    tags: true
    all_branches: true
